[package]
name = "mlchess-rs"
version = "0.1.0"
edition = "2021"

[profile.release]
opt-level = 3
lto=true
strip=true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tch = "0.13.0"
chess = "3.2.0"
